lat_dim: 128
bw_method: 0.1
device: cuda:3
model_path: models/cifar_test

data: 
    train:
        type: cifar10
        root: datasets/CIFAR10
        train: True
        batch_size: 128
        num_workers: 1
    test:
        type: cifar10
        root: datasets/CIFAR10
        train: False
        batch_size: 128
        num_workers: 1

generator:
    min_channels: 192
    max_channels: 1536
    num_blocks: 3
    normalization: ada
    lrelu_slope: 0.0
    # checkpoint:

flow:
    middle_dim: 256
    n_blocks: 100
    base_block: AllInOneBlock
    transitional_block: PermuteRandom
    # checkpoint: