n_epochs: 501
lat_dim: 128
bw_method: 0.1
device: cuda:2
model_path: models/cifar_test
exp_name: alpha_0.5_gen_1.5_laploss3_train
alpha: 0.5
clipping_value: 0.0001

# experiment:
#     api_key: CfFmqDpTCtsdDkLooedZh7bs2
#     project_name: joint-cifar
#     workspace: alexandernevarko
#     auto_metric_logging: False


data: 
    train:
        type: cifar10
        root: datasets/CIFAR10
        train: False
        batch_size: 32
        num_workers: 1
    test:
        type: cifar10
        root: datasets/CIFAR10
        train: False
        batch_size: 32
        num_workers: 1

generator:
    min_channels: 192
    max_channels: 1536
    num_blocks: 3
    normalization: ada
    lrelu_slope: 0.0
    checkpoint: pretrained/joint/alpha_0.1_100_256_flow_laploss3_test_set_generator_model.pth

flow:
    middle_dim: 256
    n_blocks: 100
    base_block: AllInOneBlock
    transitional_block: PermuteRandom
    checkpoint: pretrained/joint/alpha_0.1_100_256_flow_laploss3_test_set_flow_model.pth

g_optimizer:
    type: adam
    lr: 0.001

z_optimizer:
    type: sparse_adam
    lr: 0.001

flow_optimizer:
    type: adam
    lr: 0.001

loss:
    type: LapLoss
    params:
        max_levels: 3
        channels: 3
        size: 3
