n_epochs: 501
lat_dim: 128
bw_method: 0.1
device: cpu
model_path: models/cifar_test
alpha: 0.5
clipping_value: 0.0001

data: 
    type: cifar10
    root: datasets/CIFAR10
    batch_size: 32
    num_workers: 1

generator:
    min_channels: 128
    max_channels: 1024
    num_blocks: 3
    normalization: ada
    lrelu_slope: 0.0

flow:
    middle_dim: 256
    n_blocks: 100
    base_block: AllInOneBlock
    transitional_block: PermuteRandom

g_optimizer:
    type: adam
    lr: 0.001

z_optimizer:
    type: sparse_adam
    lr: 0.001

flow_optimizer:
    type: adam
    lr: 0.001

loss:
    type: LapLoss
    params:
        max_levels: 3
        channels: 3
        size: 3
